### ISSUE TITLE
Integrar sbadmin al proyecto

### ISSUE THREAD

**Issue by mvmarkon** [mvmarkon/desapp-unq-grupo-D-frontend#7]
Terminar de integrar sbadmin al proyecto.
-que sea responsive el header
-que sea responsive la barra de direccoinamiento que ahora es lateral

**Comment by mvmarkon** [comment]
Che ahi estaria, aunque los ultimos retoques los deje en el branch de prueba, queda el bug de que cuando se achica la pantalla el menu aparece deslpegado y si hacemos click en el sanguchito la primera vez es comosi desplegara  de vuelta el menu, asi y todo sigue siendo responsive en cuanto a resolucion

**Comment by mverdecanna** [comment]
genial... ese detalle lo vemos después si hay tiempo.  Yo espero poder
terminar lo mio hoy.

**Comment by mvmarkon** [comment]
oka, yo me meto con lo del alta de usuario en caso de no existir en la
base, cualquier cosa los pingueo

**Comment by mverdecanna** [comment]
dale!
